-- Insert admin users.

INSERT INTO public.fks_users (external_id, full_name, email, phone1, phone2, password_hash, role, status, created_at, updated_at)
VALUES 
(RANDOM_UUID(), 'Folks Admin', 'folks.admin@javalabs.org', '9000000000', NULL, '7c6a180b36896a0a8c02787eeafb0e4c', 'ADMIN', 'ACTIVE', current_timestamp, null),
(RANDOM_UUID(), 'Node Admin', 'node.admin@javalabs.org', '8000000000', NULL, '6cb75f652a9b52798eb6cf2201057c73', 'ADMIN', 'ACTIVE', current_timestamp, null),
(RANDOM_UUID(), 'Support Admin', 'support.admin@javalabs.org', '7000000000', NULL, '6cb75f652a9b52798eb6cf2201057c73', 'ADMIN', 'ACTIVE', current_timestamp, null);


-- 1. Top-level categories
INSERT INTO public.fks_categories (name, icon, tag_line, image, parent_id) 
VALUES 
('Home Services', NULL, NULL, NULL, NULL),
('Cleaning', NULL, NULL, NULL, NULL),
('Repairs', NULL, NULL, NULL, NULL),
('Beauty & Wellness', NULL, NULL, NULL, NULL),
('Appliances', NULL, NULL, NULL, NULL),
('Pest & Safety', NULL, NULL, NULL, NULL),
('Painting & Renovation', NULL, NULL, NULL, NULL),
('Moving & Shifting', NULL, NULL, NULL, NULL),
('Fitness & Therapy', NULL, NULL, NULL, NULL),
('Outdoor & Gardening', NULL, NULL, NULL, NULL),
('Maid Booking', NULL, NULL, NULL, 1),
('Laundry Pickup', NULL, NULL, NULL, 1),
('Dishwashing', NULL, NULL, NULL, 1),
('House Help', NULL, NULL, NULL, 1),
('Meal Prep', NULL, NULL, NULL, 1),
('Elder Care', NULL, NULL, NULL, 1),
('Child Care', NULL, NULL, NULL, 1),
('Home Organization', NULL, NULL, NULL, 1),
('Society Help', NULL, NULL, NULL, 1),
('Basic Home Cleaning', NULL, NULL, NULL, 2),
('Deep Cleaning', NULL, NULL, NULL, 2),
('Kitchen Cleaning', NULL, NULL, NULL, 2),
('Bathroom Cleaning', NULL, NULL, NULL, 2),
('Sofa Cleaning', NULL, NULL, NULL, 2),
('Carpet Cleaning', NULL, NULL, NULL, 2),
('Disinfection', NULL, NULL, NULL, 2),
('Water Tank Cleaning', NULL, NULL, NULL, 2),
('Post-Construction Cleaning', NULL, NULL, NULL, 2),
('Electrician', NULL, NULL, NULL, 3),
('Plumbing', NULL, NULL, NULL, 3),
('Carpentry', NULL, NULL, NULL, 3),
('AC Repair', NULL, NULL, NULL, 3),
('Appliance Repair', NULL, NULL, NULL, 3),
('TV Repair', NULL, NULL, NULL, 3),
('Geyser Repair', NULL, NULL, NULL, 3),
('Inverter Repair', NULL, NULL, NULL, 3),
('Door Repair', NULL, NULL, NULL, 3),
('Women''s Salon', NULL, NULL, NULL, 4),
('Men''s Salon', NULL, NULL, NULL, 4),
('Hair Spa', NULL, NULL, NULL, 4),
('Skin Care', NULL, NULL, NULL, 4),
('Bridal Makeup', NULL, NULL, NULL, 4),
('Waxing', NULL, NULL, NULL, 4),
('Manicure', NULL, NULL, NULL, 4),
('Pedicure', NULL, NULL, NULL, 4),
('Threading', NULL, NULL, NULL, 4),
('Washing Machine', NULL, NULL, NULL, 5),
('Refrigerator', NULL, NULL, NULL, 5),
('Microwave', NULL, NULL, NULL, 5),
('Water Purifier', NULL, NULL, NULL, 5),
('Dishwasher', NULL, NULL, NULL, 5),
('Hob & Chimney', NULL, NULL, NULL, 5),
('Mixer Grinder', NULL, NULL, NULL, 5),
('Oven', NULL, NULL, NULL, 5),
('Vacuum Cleaner', NULL, NULL, NULL, 5),
('Pest Control', NULL, NULL, NULL, 6),
('Termite Treatment', NULL, NULL, NULL, 6),
('Cockroach Control', NULL, NULL, NULL, 6),
('Bed Bug Treatment', NULL, NULL, NULL, 6),
('Mosquito Control', NULL, NULL, NULL, 6),
('Bird Net Installation', NULL, NULL, NULL, 6),
('CCTV Installation', NULL, NULL, NULL, 6),
('Fire Safety', NULL, NULL, NULL, 6),
('Home Security', NULL, NULL, NULL, 6),
('Interior Painting', NULL, NULL, NULL, 7),
('Exterior Painting', NULL, NULL, NULL, 7),
('Texture Painting', NULL, NULL, NULL, 7),
('Waterproofing', NULL, NULL, NULL, 7),
('False Ceiling', NULL, NULL, NULL, 7),
('Wall Putty', NULL, NULL, NULL, 7),
('Wood Polishing', NULL, NULL, NULL, 7),
('Tile Work', NULL, NULL, NULL, 7),
('Renovation Consultation', NULL, NULL, NULL, 7),
('Local Shifting', NULL, NULL, NULL, 8),
('Intercity Shifting', NULL, NULL, NULL, 8),
('Packing Services', NULL, NULL, NULL, 8),
('Unpacking Services', NULL, NULL, NULL, 8),
('Storage', NULL, NULL, NULL, 8),
('Bike Transport', NULL, NULL, NULL, 8),
('Office Shifting', NULL, NULL, NULL, 8),
('Furniture Moving', NULL, NULL, NULL, 8),
('Vehicle Transport', NULL, NULL, NULL, 8),
('Yoga', NULL, NULL, NULL, 9),
('Physiotherapy', NULL, NULL, NULL, 9),
('Massage', NULL, NULL, NULL, 9),
('Posture Correction', NULL, NULL, NULL, 9),
('Personal Training', NULL, NULL, NULL, 9),
('Nutrition', NULL, NULL, NULL, 9),
('Meditation', NULL, NULL, NULL, 9),
('Senior Fitness', NULL, NULL, NULL, 9),
('Prenatal Care', NULL, NULL, NULL, 9),
('Lawn Mowing', NULL, NULL, NULL, 10),
('Garden Maintenance', NULL, NULL, NULL, 10),
('Plant Care', NULL, NULL, NULL, 10),
('Soil Treatment', NULL, NULL, NULL, 10),
('Balcony Gardening', NULL, NULL, NULL, 10),
('Terrace Gardening', NULL, NULL, NULL, 10),
('Fence Repair', NULL, NULL, NULL, 10),
('Tree Pruning', NULL, NULL, NULL, 10),
('Pest Spray', NULL, NULL, NULL, 10),
('Salon & Makeup', 'scissors', 'Professional grooming and beauty services at home.', 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', NULL),
('Cleaning & Pest Control', 'broom', 'Deep cleaning and pest treatments that actually last.', 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', NULL),
('Appliance Repair', 'wrench', 'Fast, reliable repairs for the appliances you rely on daily.', 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', NULL),
('Electrician, Plumbing & Carpentry', 'bolt', 'Trusted hands for wiring, leaks and everyday fixes.', 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', NULL),
('Painting & Décor', 'paint-roller', 'Fresh coats and finishing touches, handled end to end.', 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', NULL),
('Women''s Salon', NULL, NULL, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 101),
('Men''s Salon', NULL, NULL, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop', 101),
('Bridal & Party Makeup', NULL, NULL, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 101),
('Home Cleaning', NULL, NULL, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 102),
('Pest Control', NULL, NULL, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 102),
('Office Cleaning', NULL, NULL, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 102),
('AC Service & Repair', NULL, NULL, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 103),
('Kitchen & Home Appliances', NULL, NULL, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 103),
('Electronics Repair', NULL, NULL, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 103),
('Electrician', NULL, NULL, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 104),
('Plumbing', NULL, NULL, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 104),
('Carpentry', NULL, NULL, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 104),
('Interior Painting', NULL, NULL, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 105),
('Exterior Painting', NULL, NULL, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 105);

-- 3. Services
INSERT INTO public.fks_services (category_id, name, description, base_price, currency, duration_minutes, image, rating_avg, reviews)
VALUES (11, 'Basic Maid Booking', 'Basic package for maid booking under home services. Includes trained professionals, standard tools, and service support.', 304.00, 'INR', 63, NULL, NULL, NULL),
(11, 'Standard Maid Booking', 'Standard package for maid booking under home services. Includes trained professionals, standard tools, and service support.', 497.00, 'INR', 104, NULL, NULL, NULL),
(11, 'Premium Maid Booking', 'Premium package for maid booking under home services. Includes trained professionals, standard tools, and service support.', 644.00, 'INR', 130, NULL, NULL, NULL),
(12, 'Basic Laundry Pickup', 'Basic package for laundry pickup under home services. Includes trained professionals, standard tools, and service support.', 304.00, 'INR', 68, NULL, NULL, NULL),
(12, 'Standard Laundry Pickup', 'Standard package for laundry pickup under home services. Includes trained professionals, standard tools, and service support.', 468.00, 'INR', 98, NULL, NULL, NULL),
(12, 'Premium Laundry Pickup', 'Premium package for laundry pickup under home services. Includes trained professionals, standard tools, and service support.', 631.00, 'INR', 122, NULL, NULL, NULL),
(13, 'Basic Dishwashing', 'Basic package for dishwashing under home services. Includes trained professionals, standard tools, and service support.', 350.00, 'INR', 72, NULL, NULL, NULL),
(13, 'Standard Dishwashing', 'Standard package for dishwashing under home services. Includes trained professionals, standard tools, and service support.', 475.00, 'INR', 92, NULL, NULL, NULL),
(13, 'Premium Dishwashing', 'Premium package for dishwashing under home services. Includes trained professionals, standard tools, and service support.', 605.00, 'INR', 120, NULL, NULL, NULL),
(14, 'Basic House Help', 'Basic package for house help under home services. Includes trained professionals, standard tools, and service support.', 342.00, 'INR', 74, NULL, NULL, NULL),
(14, 'Standard House Help', 'Standard package for house help under home services. Includes trained professionals, standard tools, and service support.', 499.00, 'INR', 103, NULL, NULL, NULL),
(14, 'Premium House Help', 'Premium package for house help under home services. Includes trained professionals, standard tools, and service support.', 625.00, 'INR', 123, NULL, NULL, NULL),
(15, 'Basic Meal Prep', 'Basic package for meal prep under home services. Includes trained professionals, standard tools, and service support.', 367.00, 'INR', 66, NULL, NULL, NULL),
(15, 'Standard Meal Prep', 'Standard package for meal prep under home services. Includes trained professionals, standard tools, and service support.', 504.00, 'INR', 103, NULL, NULL, NULL),
(15, 'Premium Meal Prep', 'Premium package for meal prep under home services. Includes trained professionals, standard tools, and service support.', 636.00, 'INR', 126, NULL, NULL, NULL),
(16, 'Basic Elder Care', 'Basic package for elder care under home services. Includes trained professionals, standard tools, and service support.', 354.00, 'INR', 66, NULL, NULL, NULL),
(16, 'Standard Elder Care', 'Standard package for elder care under home services. Includes trained professionals, standard tools, and service support.', 454.00, 'INR', 95, NULL, NULL, NULL),
(16, 'Premium Elder Care', 'Premium package for elder care under home services. Includes trained professionals, standard tools, and service support.', 616.00, 'INR', 122, NULL, NULL, NULL),
(17, 'Basic Child Care', 'Basic package for child care under home services. Includes trained professionals, standard tools, and service support.', 311.00, 'INR', 73, NULL, NULL, NULL),
(17, 'Standard Child Care', 'Standard package for child care under home services. Includes trained professionals, standard tools, and service support.', 462.00, 'INR', 99, NULL, NULL, NULL),
(17, 'Premium Child Care', 'Premium package for child care under home services. Includes trained professionals, standard tools, and service support.', 628.00, 'INR', 130, NULL, NULL, NULL),
(18, 'Basic Home Organization', 'Basic package for home organization under home services. Includes trained professionals, standard tools, and service support.', 322.00, 'INR', 67, NULL, NULL, NULL),
(18, 'Standard Home Organization', 'Standard package for home organization under home services. Includes trained professionals, standard tools, and service support.', 499.00, 'INR', 99, NULL, NULL, NULL),
(18, 'Premium Home Organization', 'Premium package for home organization under home services. Includes trained professionals, standard tools, and service support.', 606.00, 'INR', 125, NULL, NULL, NULL),
(19, 'Basic Society Help', 'Basic package for society help under home services. Includes trained professionals, standard tools, and service support.', 306.00, 'INR', 73, NULL, NULL, NULL),
(19, 'Standard Society Help', 'Standard package for society help under home services. Includes trained professionals, standard tools, and service support.', 492.00, 'INR', 95, NULL, NULL, NULL),
(19, 'Premium Society Help', 'Premium package for society help under home services. Includes trained professionals, standard tools, and service support.', 607.00, 'INR', 121, NULL, NULL, NULL),
(20, 'Basic Basic Home Cleaning', 'Basic package for basic home cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 534.00, 'INR', 130, NULL, NULL, NULL),
(20, 'Standard Basic Home Cleaning', 'Standard package for basic home cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 662.00, 'INR', 154, NULL, NULL, NULL),
(20, 'Premium Basic Home Cleaning', 'Premium package for basic home cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 835.00, 'INR', 183, NULL, NULL, NULL),
(21, 'Basic Deep Cleaning', 'Basic package for deep cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 521.00, 'INR', 134, NULL, NULL, NULL),
(21, 'Standard Deep Cleaning', 'Standard package for deep cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 651.00, 'INR', 151, NULL, NULL, NULL),
(21, 'Premium Deep Cleaning', 'Premium package for deep cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 843.00, 'INR', 194, NULL, NULL, NULL),
(22, 'Basic Kitchen Cleaning', 'Basic package for kitchen cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 522.00, 'INR', 124, NULL, NULL, NULL),
(22, 'Standard Kitchen Cleaning', 'Standard package for kitchen cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 649.00, 'INR', 159, NULL, NULL, NULL),
(22, 'Premium Kitchen Cleaning', 'Premium package for kitchen cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 839.00, 'INR', 191, NULL, NULL, NULL),
(23, 'Basic Bathroom Cleaning', 'Basic package for bathroom cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 527.00, 'INR', 124, NULL, NULL, NULL),
(23, 'Standard Bathroom Cleaning', 'Standard package for bathroom cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 722.00, 'INR', 158, NULL, NULL, NULL),
(23, 'Premium Bathroom Cleaning', 'Premium package for bathroom cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 810.00, 'INR', 190, NULL, NULL, NULL),
(24, 'Basic Sofa Cleaning', 'Basic package for sofa cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 549.00, 'INR', 123, NULL, NULL, NULL),
(24, 'Standard Sofa Cleaning', 'Standard package for sofa cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 649.00, 'INR', 154, NULL, NULL, NULL),
(24, 'Premium Sofa Cleaning', 'Premium package for sofa cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 852.00, 'INR', 182, NULL, NULL, NULL),
(25, 'Basic Carpet Cleaning', 'Basic package for carpet cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 506.00, 'INR', 123, NULL, NULL, NULL),
(25, 'Standard Carpet Cleaning', 'Standard package for carpet cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 658.00, 'INR', 159, NULL, NULL, NULL),
(25, 'Premium Carpet Cleaning', 'Premium package for carpet cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 822.00, 'INR', 184, NULL, NULL, NULL),
(26, 'Basic Disinfection', 'Basic package for disinfection under cleaning. Includes trained professionals, standard tools, and service support.', 571.00, 'INR', 126, NULL, NULL, NULL),
(26, 'Standard Disinfection', 'Standard package for disinfection under cleaning. Includes trained professionals, standard tools, and service support.', 697.00, 'INR', 150, NULL, NULL, NULL),
(26, 'Premium Disinfection', 'Premium package for disinfection under cleaning. Includes trained professionals, standard tools, and service support.', 858.00, 'INR', 183, NULL, NULL, NULL),
(27, 'Basic Water Tank Cleaning', 'Basic package for water tank cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 553.00, 'INR', 126, NULL, NULL, NULL),
(27, 'Standard Water Tank Cleaning', 'Standard package for water tank cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 675.00, 'INR', 163, NULL, NULL, NULL),
(27, 'Premium Water Tank Cleaning', 'Premium package for water tank cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 844.00, 'INR', 190, NULL, NULL, NULL),
(28, 'Basic Post-Construction Cleaning', 'Basic package for post-construction cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 556.00, 'INR', 124, NULL, NULL, NULL),
(28, 'Standard Post-Construction Cleaning', 'Standard package for post-construction cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 657.00, 'INR', 151, NULL, NULL, NULL),
(28, 'Premium Post-Construction Cleaning', 'Premium package for post-construction cleaning under cleaning. Includes trained professionals, standard tools, and service support.', 808.00, 'INR', 191, NULL, NULL, NULL),
(29, 'Basic Electrician', 'Basic package for electrician under repairs. Includes trained professionals, standard tools, and service support.', 374.00, 'INR', 47, NULL, NULL, NULL),
(29, 'Standard Electrician', 'Standard package for electrician under repairs. Includes trained professionals, standard tools, and service support.', 570.00, 'INR', 79, NULL, NULL, NULL),
(29, 'Premium Electrician', 'Premium package for electrician under repairs. Includes trained professionals, standard tools, and service support.', 721.00, 'INR', 106, NULL, NULL, NULL),
(30, 'Basic Plumbing', 'Basic package for plumbing under repairs. Includes trained professionals, standard tools, and service support.', 355.00, 'INR', 45, NULL, NULL, NULL),
(30, 'Standard Plumbing', 'Standard package for plumbing under repairs. Includes trained professionals, standard tools, and service support.', 530.00, 'INR', 85, NULL, NULL, NULL),
(30, 'Premium Plumbing', 'Premium package for plumbing under repairs. Includes trained professionals, standard tools, and service support.', 705.00, 'INR', 114, NULL, NULL, NULL),
(31, 'Basic Carpentry', 'Basic package for carpentry under repairs. Includes trained professionals, standard tools, and service support.', 370.00, 'INR', 48, NULL, NULL, NULL),
(31, 'Standard Carpentry', 'Standard package for carpentry under repairs. Includes trained professionals, standard tools, and service support.', 507.00, 'INR', 88, NULL, NULL, NULL),
(31, 'Premium Carpentry', 'Premium package for carpentry under repairs. Includes trained professionals, standard tools, and service support.', 651.00, 'INR', 117, NULL, NULL, NULL),
(32, 'Basic AC Repair', 'Basic package for ac repair under repairs. Includes trained professionals, standard tools, and service support.', 371.00, 'INR', 48, NULL, NULL, NULL),
(32, 'Standard AC Repair', 'Standard package for ac repair under repairs. Includes trained professionals, standard tools, and service support.', 557.00, 'INR', 82, NULL, NULL, NULL),
(32, 'Premium AC Repair', 'Premium package for ac repair under repairs. Includes trained professionals, standard tools, and service support.', 701.00, 'INR', 107, NULL, NULL, NULL),
(33, 'Basic Appliance Repair', 'Basic package for appliance repair under repairs. Includes trained professionals, standard tools, and service support.', 362.00, 'INR', 52, NULL, NULL, NULL),
(33, 'Standard Appliance Repair', 'Standard package for appliance repair under repairs. Includes trained professionals, standard tools, and service support.', 571.00, 'INR', 83, NULL, NULL, NULL),
(33, 'Premium Appliance Repair', 'Premium package for appliance repair under repairs. Includes trained professionals, standard tools, and service support.', 649.00, 'INR', 107, NULL, NULL, NULL),
(34, 'Basic TV Repair', 'Basic package for tv repair under repairs. Includes trained professionals, standard tools, and service support.', 351.00, 'INR', 58, NULL, NULL, NULL),
(34, 'Standard TV Repair', 'Standard package for tv repair under repairs. Includes trained professionals, standard tools, and service support.', 522.00, 'INR', 77, NULL, NULL, NULL),
(34, 'Premium TV Repair', 'Premium package for tv repair under repairs. Includes trained professionals, standard tools, and service support.', 695.00, 'INR', 113, NULL, NULL, NULL),
(35, 'Basic Geyser Repair', 'Basic package for geyser repair under repairs. Includes trained professionals, standard tools, and service support.', 378.00, 'INR', 53, NULL, NULL, NULL),
(35, 'Standard Geyser Repair', 'Standard package for geyser repair under repairs. Includes trained professionals, standard tools, and service support.', 502.00, 'INR', 83, NULL, NULL, NULL),
(35, 'Premium Geyser Repair', 'Premium package for geyser repair under repairs. Includes trained professionals, standard tools, and service support.', 671.00, 'INR', 116, NULL, NULL, NULL),
(36, 'Basic Inverter Repair', 'Basic package for inverter repair under repairs. Includes trained professionals, standard tools, and service support.', 404.00, 'INR', 50, NULL, NULL, NULL),
(36, 'Standard Inverter Repair', 'Standard package for inverter repair under repairs. Includes trained professionals, standard tools, and service support.', 570.00, 'INR', 75, NULL, NULL, NULL),
(36, 'Premium Inverter Repair', 'Premium package for inverter repair under repairs. Includes trained professionals, standard tools, and service support.', 680.00, 'INR', 109, NULL, NULL, NULL),
(37, 'Basic Door Repair', 'Basic package for door repair under repairs. Includes trained professionals, standard tools, and service support.', 399.00, 'INR', 56, NULL, NULL, NULL),
(37, 'Standard Door Repair', 'Standard package for door repair under repairs. Includes trained professionals, standard tools, and service support.', 516.00, 'INR', 81, NULL, NULL, NULL),
(37, 'Premium Door Repair', 'Premium package for door repair under repairs. Includes trained professionals, standard tools, and service support.', 683.00, 'INR', 111, NULL, NULL, NULL),
(38, 'Basic Women''s Salon', 'Basic package for women''s salon under beauty & wellness. Includes trained professionals, standard tools, and service support.', 464.00, 'INR', 50, NULL, NULL, NULL),
(38, 'Standard Women''s Salon', 'Standard package for women''s salon under beauty & wellness. Includes trained professionals, standard tools, and service support.', 589.00, 'INR', 75, NULL, NULL, NULL),
(38, 'Premium Women''s Salon', 'Premium package for women''s salon under beauty & wellness. Includes trained professionals, standard tools, and service support.', 704.00, 'INR', 114, NULL, NULL, NULL),
(39, 'Basic Men''s Salon', 'Basic package for men''s salon under beauty & wellness. Includes trained professionals, standard tools, and service support.', 428.00, 'INR', 46, NULL, NULL, NULL),
(39, 'Standard Men''s Salon', 'Standard package for men''s salon under beauty & wellness. Includes trained professionals, standard tools, and service support.', 623.00, 'INR', 89, NULL, NULL, NULL),
(39, 'Premium Men''s Salon', 'Premium package for men''s salon under beauty & wellness. Includes trained professionals, standard tools, and service support.', 765.00, 'INR', 108, NULL, NULL, NULL),
(40, 'Basic Hair Spa', 'Basic package for hair spa under beauty & wellness. Includes trained professionals, standard tools, and service support.', 430.00, 'INR', 51, NULL, NULL, NULL),
(40, 'Standard Hair Spa', 'Standard package for hair spa under beauty & wellness. Includes trained professionals, standard tools, and service support.', 561.00, 'INR', 81, NULL, NULL, NULL),
(40, 'Premium Hair Spa', 'Premium package for hair spa under beauty & wellness. Includes trained professionals, standard tools, and service support.', 703.00, 'INR', 112, NULL, NULL, NULL),
(41, 'Basic Skin Care', 'Basic package for skin care under beauty & wellness. Includes trained professionals, standard tools, and service support.', 470.00, 'INR', 49, NULL, NULL, NULL),
(41, 'Standard Skin Care', 'Standard package for skin care under beauty & wellness. Includes trained professionals, standard tools, and service support.', 584.00, 'INR', 79, NULL, NULL, NULL),
(41, 'Premium Skin Care', 'Premium package for skin care under beauty & wellness. Includes trained professionals, standard tools, and service support.', 723.00, 'INR', 110, NULL, NULL, NULL),
(42, 'Basic Bridal Makeup', 'Basic package for bridal makeup under beauty & wellness. Includes trained professionals, standard tools, and service support.', 435.00, 'INR', 45, NULL, NULL, NULL),
(42, 'Standard Bridal Makeup', 'Standard package for bridal makeup under beauty & wellness. Includes trained professionals, standard tools, and service support.', 591.00, 'INR', 81, NULL, NULL, NULL),
(42, 'Premium Bridal Makeup', 'Premium package for bridal makeup under beauty & wellness. Includes trained professionals, standard tools, and service support.', 722.00, 'INR', 108, NULL, NULL, NULL),
(43, 'Basic Waxing', 'Basic package for waxing under beauty & wellness. Includes trained professionals, standard tools, and service support.', 440.00, 'INR', 58, NULL, NULL, NULL),
(43, 'Standard Waxing', 'Standard package for waxing under beauty & wellness. Includes trained professionals, standard tools, and service support.', 615.00, 'INR', 89, NULL, NULL, NULL),
(43, 'Premium Waxing', 'Premium package for waxing under beauty & wellness. Includes trained professionals, standard tools, and service support.', 713.00, 'INR', 113, NULL, NULL, NULL),
(44, 'Basic Manicure', 'Basic package for manicure under beauty & wellness. Includes trained professionals, standard tools, and service support.', 442.00, 'INR', 54, NULL, NULL, NULL),
(44, 'Standard Manicure', 'Standard package for manicure under beauty & wellness. Includes trained professionals, standard tools, and service support.', 558.00, 'INR', 83, NULL, NULL, NULL),
(44, 'Premium Manicure', 'Premium package for manicure under beauty & wellness. Includes trained professionals, standard tools, and service support.', 702.00, 'INR', 113, NULL, NULL, NULL),
(45, 'Basic Pedicure', 'Basic package for pedicure under beauty & wellness. Includes trained professionals, standard tools, and service support.', 443.00, 'INR', 52, NULL, NULL, NULL),
(45, 'Standard Pedicure', 'Standard package for pedicure under beauty & wellness. Includes trained professionals, standard tools, and service support.', 621.00, 'INR', 76, NULL, NULL, NULL),
(45, 'Premium Pedicure', 'Premium package for pedicure under beauty & wellness. Includes trained professionals, standard tools, and service support.', 703.00, 'INR', 110, NULL, NULL, NULL),
(46, 'Basic Threading', 'Basic package for threading under beauty & wellness. Includes trained professionals, standard tools, and service support.', 399.00, 'INR', 58, NULL, NULL, NULL),
(46, 'Standard Threading', 'Standard package for threading under beauty & wellness. Includes trained professionals, standard tools, and service support.', 587.00, 'INR', 88, NULL, NULL, NULL),
(46, 'Premium Threading', 'Premium package for threading under beauty & wellness. Includes trained professionals, standard tools, and service support.', 718.00, 'INR', 115, NULL, NULL, NULL),
(47, 'Basic Washing Machine', 'Basic package for washing machine under appliances. Includes trained professionals, standard tools, and service support.', 508.00, 'INR', 71, NULL, NULL, NULL),
(47, 'Standard Washing Machine', 'Standard package for washing machine under appliances. Includes trained professionals, standard tools, and service support.', 607.00, 'INR', 103, NULL, NULL, NULL),
(47, 'Premium Washing Machine', 'Premium package for washing machine under appliances. Includes trained professionals, standard tools, and service support.', 799.00, 'INR', 131, NULL, NULL, NULL),
(48, 'Basic Refrigerator', 'Basic package for refrigerator under appliances. Includes trained professionals, standard tools, and service support.', 510.00, 'INR', 68, NULL, NULL, NULL),
(48, 'Standard Refrigerator', 'Standard package for refrigerator under appliances. Includes trained professionals, standard tools, and service support.', 647.00, 'INR', 98, NULL, NULL, NULL),
(48, 'Premium Refrigerator', 'Premium package for refrigerator under appliances. Includes trained professionals, standard tools, and service support.', 765.00, 'INR', 133, NULL, NULL, NULL),
(49, 'Basic Microwave', 'Basic package for microwave under appliances. Includes trained professionals, standard tools, and service support.', 498.00, 'INR', 67, NULL, NULL, NULL),
(49, 'Standard Microwave', 'Standard package for microwave under appliances. Includes trained professionals, standard tools, and service support.', 629.00, 'INR', 97, NULL, NULL, NULL),
(49, 'Premium Microwave', 'Premium package for microwave under appliances. Includes trained professionals, standard tools, and service support.', 792.00, 'INR', 132, NULL, NULL, NULL),
(50, 'Basic Water Purifier', 'Basic package for water purifier under appliances. Includes trained professionals, standard tools, and service support.', 515.00, 'INR', 69, NULL, NULL, NULL),
(50, 'Standard Water Purifier', 'Standard package for water purifier under appliances. Includes trained professionals, standard tools, and service support.', 636.00, 'INR', 90, NULL, NULL, NULL),
(50, 'Premium Water Purifier', 'Premium package for water purifier under appliances. Includes trained professionals, standard tools, and service support.', 802.00, 'INR', 120, NULL, NULL, NULL),
(51, 'Basic Dishwasher', 'Basic package for dishwasher under appliances. Includes trained professionals, standard tools, and service support.', 485.00, 'INR', 66, NULL, NULL, NULL),
(51, 'Standard Dishwasher', 'Standard package for dishwasher under appliances. Includes trained professionals, standard tools, and service support.', 655.00, 'INR', 100, NULL, NULL, NULL),
(51, 'Premium Dishwasher', 'Premium package for dishwasher under appliances. Includes trained professionals, standard tools, and service support.', 812.00, 'INR', 126, NULL, NULL, NULL),
(52, 'Basic Hob & Chimney', 'Basic package for hob & chimney under appliances. Includes trained professionals, standard tools, and service support.', 465.00, 'INR', 71, NULL, NULL, NULL),
(52, 'Standard Hob & Chimney', 'Standard package for hob & chimney under appliances. Includes trained professionals, standard tools, and service support.', 629.00, 'INR', 100, NULL, NULL, NULL),
(52, 'Premium Hob & Chimney', 'Premium package for hob & chimney under appliances. Includes trained professionals, standard tools, and service support.', 767.00, 'INR', 120, NULL, NULL, NULL),
(53, 'Basic Mixer Grinder', 'Basic package for mixer grinder under appliances. Includes trained professionals, standard tools, and service support.', 505.00, 'INR', 60, NULL, NULL, NULL),
(53, 'Standard Mixer Grinder', 'Standard package for mixer grinder under appliances. Includes trained professionals, standard tools, and service support.', 602.00, 'INR', 90, NULL, NULL, NULL),
(53, 'Premium Mixer Grinder', 'Premium package for mixer grinder under appliances. Includes trained professionals, standard tools, and service support.', 808.00, 'INR', 129, NULL, NULL, NULL),
(54, 'Basic Oven', 'Basic package for oven under appliances. Includes trained professionals, standard tools, and service support.', 464.00, 'INR', 61, NULL, NULL, NULL),
(54, 'Standard Oven', 'Standard package for oven under appliances. Includes trained professionals, standard tools, and service support.', 607.00, 'INR', 99, NULL, NULL, NULL),
(54, 'Premium Oven', 'Premium package for oven under appliances. Includes trained professionals, standard tools, and service support.', 809.00, 'INR', 121, NULL, NULL, NULL),
(55, 'Basic Vacuum Cleaner', 'Basic package for vacuum cleaner under appliances. Includes trained professionals, standard tools, and service support.', 513.00, 'INR', 67, NULL, NULL, NULL),
(55, 'Standard Vacuum Cleaner', 'Standard package for vacuum cleaner under appliances. Includes trained professionals, standard tools, and service support.', 664.00, 'INR', 92, NULL, NULL, NULL),
(55, 'Premium Vacuum Cleaner', 'Premium package for vacuum cleaner under appliances. Includes trained professionals, standard tools, and service support.', 773.00, 'INR', 126, NULL, NULL, NULL),
(56, 'Basic Pest Control', 'Basic package for pest control under pest & safety. Includes trained professionals, standard tools, and service support.', 843.00, 'INR', 90, NULL, NULL, NULL),
(56, 'Standard Pest Control', 'Standard package for pest control under pest & safety. Includes trained professionals, standard tools, and service support.', 1012.00, 'INR', 121, NULL, NULL, NULL),
(56, 'Premium Pest Control', 'Premium package for pest control under pest & safety. Includes trained professionals, standard tools, and service support.', 1134.00, 'INR', 159, NULL, NULL, NULL),
(57, 'Basic Termite Treatment', 'Basic package for termite treatment under pest & safety. Includes trained professionals, standard tools, and service support.', 835.00, 'INR', 91, NULL, NULL, NULL),
(57, 'Standard Termite Treatment', 'Standard package for termite treatment under pest & safety. Includes trained professionals, standard tools, and service support.', 967.00, 'INR', 127, NULL, NULL, NULL),
(57, 'Premium Termite Treatment', 'Premium package for termite treatment under pest & safety. Includes trained professionals, standard tools, and service support.', 1166.00, 'INR', 164, NULL, NULL, NULL),
(58, 'Basic Cockroach Control', 'Basic package for cockroach control under pest & safety. Includes trained professionals, standard tools, and service support.', 826.00, 'INR', 102, NULL, NULL, NULL),
(58, 'Standard Cockroach Control', 'Standard package for cockroach control under pest & safety. Includes trained professionals, standard tools, and service support.', 959.00, 'INR', 126, NULL, NULL, NULL),
(58, 'Premium Cockroach Control', 'Premium package for cockroach control under pest & safety. Includes trained professionals, standard tools, and service support.', 1118.00, 'INR', 158, NULL, NULL, NULL),
(59, 'Basic Bed Bug Treatment', 'Basic package for bed bug treatment under pest & safety. Includes trained professionals, standard tools, and service support.', 799.00, 'INR', 95, NULL, NULL, NULL),
(59, 'Standard Bed Bug Treatment', 'Standard package for bed bug treatment under pest & safety. Includes trained professionals, standard tools, and service support.', 964.00, 'INR', 123, NULL, NULL, NULL),
(59, 'Premium Bed Bug Treatment', 'Premium package for bed bug treatment under pest & safety. Includes trained professionals, standard tools, and service support.', 1118.00, 'INR', 152, NULL, NULL, NULL),
(60, 'Basic Mosquito Control', 'Basic package for mosquito control under pest & safety. Includes trained professionals, standard tools, and service support.', 831.00, 'INR', 92, NULL, NULL, NULL),
(60, 'Standard Mosquito Control', 'Standard package for mosquito control under pest & safety. Includes trained professionals, standard tools, and service support.', 1012.00, 'INR', 130, NULL, NULL, NULL),
(60, 'Premium Mosquito Control', 'Premium package for mosquito control under pest & safety. Includes trained professionals, standard tools, and service support.', 1140.00, 'INR', 163, NULL, NULL, NULL),
(61, 'Basic Bird Net Installation', 'Basic package for bird net installation under pest & safety. Includes trained professionals, standard tools, and service support.', 846.00, 'INR', 94, NULL, NULL, NULL),
(61, 'Standard Bird Net Installation', 'Standard package for bird net installation under pest & safety. Includes trained professionals, standard tools, and service support.', 958.00, 'INR', 126, NULL, NULL, NULL),
(61, 'Premium Bird Net Installation', 'Premium package for bird net installation under pest & safety. Includes trained professionals, standard tools, and service support.', 1159.00, 'INR', 159, NULL, NULL, NULL),
(62, 'Basic CCTV Installation', 'Basic package for cctv installation under pest & safety. Includes trained professionals, standard tools, and service support.', 812.00, 'INR', 103, NULL, NULL, NULL),
(62, 'Standard CCTV Installation', 'Standard package for cctv installation under pest & safety. Includes trained professionals, standard tools, and service support.', 965.00, 'INR', 122, NULL, NULL, NULL),
(62, 'Premium CCTV Installation', 'Premium package for cctv installation under pest & safety. Includes trained professionals, standard tools, and service support.', 1164.00, 'INR', 158, NULL, NULL, NULL),
(63, 'Basic Fire Safety', 'Basic package for fire safety under pest & safety. Includes trained professionals, standard tools, and service support.', 833.00, 'INR', 104, NULL, NULL, NULL),
(63, 'Standard Fire Safety', 'Standard package for fire safety under pest & safety. Includes trained professionals, standard tools, and service support.', 1017.00, 'INR', 134, NULL, NULL, NULL),
(63, 'Premium Fire Safety', 'Premium package for fire safety under pest & safety. Includes trained professionals, standard tools, and service support.', 1154.00, 'INR', 163, NULL, NULL, NULL),
(64, 'Basic Home Security', 'Basic package for home security under pest & safety. Includes trained professionals, standard tools, and service support.', 829.00, 'INR', 95, NULL, NULL, NULL),
(64, 'Standard Home Security', 'Standard package for home security under pest & safety. Includes trained professionals, standard tools, and service support.', 961.00, 'INR', 130, NULL, NULL, NULL),
(64, 'Premium Home Security', 'Premium package for home security under pest & safety. Includes trained professionals, standard tools, and service support.', 1168.00, 'INR', 154, NULL, NULL, NULL),
(65, 'Basic Interior Painting', 'Basic package for interior painting under painting & renovation. Includes trained professionals, standard tools, and service support.', 1537.00, 'INR', 183, NULL, NULL, NULL),
(65, 'Standard Interior Painting', 'Standard package for interior painting under painting & renovation. Includes trained professionals, standard tools, and service support.', 1678.00, 'INR', 221, NULL, NULL, NULL),
(65, 'Premium Interior Painting', 'Premium package for interior painting under painting & renovation. Includes trained professionals, standard tools, and service support.', 1835.00, 'INR', 252, NULL, NULL, NULL),
(66, 'Basic Exterior Painting', 'Basic package for exterior painting under painting & renovation. Includes trained professionals, standard tools, and service support.', 1522.00, 'INR', 188, NULL, NULL, NULL),
(66, 'Standard Exterior Painting', 'Standard package for exterior painting under painting & renovation. Includes trained professionals, standard tools, and service support.', 1690.00, 'INR', 217, NULL, NULL, NULL),
(66, 'Premium Exterior Painting', 'Premium package for exterior painting under painting & renovation. Includes trained professionals, standard tools, and service support.', 1810.00, 'INR', 251, NULL, NULL, NULL),
(67, 'Basic Texture Painting', 'Basic package for texture painting under painting & renovation. Includes trained professionals, standard tools, and service support.', 1506.00, 'INR', 193, NULL, NULL, NULL),
(67, 'Standard Texture Painting', 'Standard package for texture painting under painting & renovation. Includes trained professionals, standard tools, and service support.', 1695.00, 'INR', 221, NULL, NULL, NULL),
(67, 'Premium Texture Painting', 'Premium package for texture painting under painting & renovation. Includes trained professionals, standard tools, and service support.', 1808.00, 'INR', 249, NULL, NULL, NULL),
(68, 'Basic Waterproofing', 'Basic package for waterproofing under painting & renovation. Includes trained professionals, standard tools, and service support.', 1556.00, 'INR', 186, NULL, NULL, NULL),
(68, 'Standard Waterproofing', 'Standard package for waterproofing under painting & renovation. Includes trained professionals, standard tools, and service support.', 1710.00, 'INR', 218, NULL, NULL, NULL),
(68, 'Premium Waterproofing', 'Premium package for waterproofing under painting & renovation. Includes trained professionals, standard tools, and service support.', 1866.00, 'INR', 243, NULL, NULL, NULL),
(69, 'Basic False Ceiling', 'Basic package for false ceiling under painting & renovation. Includes trained professionals, standard tools, and service support.', 1508.00, 'INR', 188, NULL, NULL, NULL),
(69, 'Standard False Ceiling', 'Standard package for false ceiling under painting & renovation. Includes trained professionals, standard tools, and service support.', 1673.00, 'INR', 217, NULL, NULL, NULL),
(69, 'Premium False Ceiling', 'Premium package for false ceiling under painting & renovation. Includes trained professionals, standard tools, and service support.', 1865.00, 'INR', 246, NULL, NULL, NULL),
(70, 'Basic Wall Putty', 'Basic package for wall putty under painting & renovation. Includes trained professionals, standard tools, and service support.', 1559.00, 'INR', 184, NULL, NULL, NULL),
(70, 'Standard Wall Putty', 'Standard package for wall putty under painting & renovation. Includes trained professionals, standard tools, and service support.', 1680.00, 'INR', 212, NULL, NULL, NULL),
(70, 'Premium Wall Putty', 'Premium package for wall putty under painting & renovation. Includes trained professionals, standard tools, and service support.', 1806.00, 'INR', 247, NULL, NULL, NULL),
(71, 'Basic Wood Polishing', 'Basic package for wood polishing under painting & renovation. Includes trained professionals, standard tools, and service support.', 1522.00, 'INR', 182, NULL, NULL, NULL),
(71, 'Standard Wood Polishing', 'Standard package for wood polishing under painting & renovation. Includes trained professionals, standard tools, and service support.', 1679.00, 'INR', 217, NULL, NULL, NULL),
(71, 'Premium Wood Polishing', 'Premium package for wood polishing under painting & renovation. Includes trained professionals, standard tools, and service support.', 1830.00, 'INR', 249, NULL, NULL, NULL),
(72, 'Basic Tile Work', 'Basic package for tile work under painting & renovation. Includes trained professionals, standard tools, and service support.', 1564.00, 'INR', 186, NULL, NULL, NULL),
(72, 'Standard Tile Work', 'Standard package for tile work under painting & renovation. Includes trained professionals, standard tools, and service support.', 1720.00, 'INR', 215, NULL, NULL, NULL),
(72, 'Premium Tile Work', 'Premium package for tile work under painting & renovation. Includes trained professionals, standard tools, and service support.', 1844.00, 'INR', 246, NULL, NULL, NULL),
(73, 'Basic Renovation Consultation', 'Basic package for renovation consultation under painting & renovation. Includes trained professionals, standard tools, and service support.', 1542.00, 'INR', 186, NULL, NULL, NULL),
(73, 'Standard Renovation Consultation', 'Standard package for renovation consultation under painting & renovation. Includes trained professionals, standard tools, and service support.', 1651.00, 'INR', 211, NULL, NULL, NULL),
(73, 'Premium Renovation Consultation', 'Premium package for renovation consultation under painting & renovation. Includes trained professionals, standard tools, and service support.', 1803.00, 'INR', 254, NULL, NULL, NULL),
(74, 'Basic Local Shifting', 'Basic package for local shifting under moving & shifting. Includes trained professionals, standard tools, and service support.', 1064.00, 'INR', 133, NULL, NULL, NULL),
(74, 'Standard Local Shifting', 'Standard package for local shifting under moving & shifting. Includes trained professionals, standard tools, and service support.', 1176.00, 'INR', 152, NULL, NULL, NULL),
(74, 'Premium Local Shifting', 'Premium package for local shifting under moving & shifting. Includes trained professionals, standard tools, and service support.', 1326.00, 'INR', 190, NULL, NULL, NULL),
(75, 'Basic Intercity Shifting', 'Basic package for intercity shifting under moving & shifting. Includes trained professionals, standard tools, and service support.', 1026.00, 'INR', 122, NULL, NULL, NULL),
(75, 'Standard Intercity Shifting', 'Standard package for intercity shifting under moving & shifting. Includes trained professionals, standard tools, and service support.', 1166.00, 'INR', 160, NULL, NULL, NULL),
(75, 'Premium Intercity Shifting', 'Premium package for intercity shifting under moving & shifting. Includes trained professionals, standard tools, and service support.', 1364.00, 'INR', 186, NULL, NULL, NULL),
(76, 'Basic Packing Services', 'Basic package for packing services under moving & shifting. Includes trained professionals, standard tools, and service support.', 1031.00, 'INR', 130, NULL, NULL, NULL),
(76, 'Standard Packing Services', 'Standard package for packing services under moving & shifting. Includes trained professionals, standard tools, and service support.', 1172.00, 'INR', 164, NULL, NULL, NULL),
(76, 'Premium Packing Services', 'Premium package for packing services under moving & shifting. Includes trained professionals, standard tools, and service support.', 1354.00, 'INR', 191, NULL, NULL, NULL),
(77, 'Basic Unpacking Services', 'Basic package for unpacking services under moving & shifting. Includes trained professionals, standard tools, and service support.', 1041.00, 'INR', 131, NULL, NULL, NULL),
(77, 'Standard Unpacking Services', 'Standard package for unpacking services under moving & shifting. Includes trained professionals, standard tools, and service support.', 1191.00, 'INR', 160, NULL, NULL, NULL),
(77, 'Premium Unpacking Services', 'Premium package for unpacking services under moving & shifting. Includes trained professionals, standard tools, and service support.', 1342.00, 'INR', 187, NULL, NULL, NULL),
(78, 'Basic Storage', 'Basic package for storage under moving & shifting. Includes trained professionals, standard tools, and service support.', 1021.00, 'INR', 128, NULL, NULL, NULL),
(78, 'Standard Storage', 'Standard package for storage under moving & shifting. Includes trained professionals, standard tools, and service support.', 1177.00, 'INR', 158, NULL, NULL, NULL),
(78, 'Premium Storage', 'Premium package for storage under moving & shifting. Includes trained professionals, standard tools, and service support.', 1342.00, 'INR', 191, NULL, NULL, NULL),
(79, 'Basic Bike Transport', 'Basic package for bike transport under moving & shifting. Includes trained professionals, standard tools, and service support.', 1059.00, 'INR', 127, NULL, NULL, NULL),
(79, 'Standard Bike Transport', 'Standard package for bike transport under moving & shifting. Includes trained professionals, standard tools, and service support.', 1219.00, 'INR', 156, NULL, NULL, NULL),
(79, 'Premium Bike Transport', 'Premium package for bike transport under moving & shifting. Includes trained professionals, standard tools, and service support.', 1336.00, 'INR', 183, NULL, NULL, NULL),
(80, 'Basic Office Shifting', 'Basic package for office shifting under moving & shifting. Includes trained professionals, standard tools, and service support.', 1057.00, 'INR', 129, NULL, NULL, NULL),
(80, 'Standard Office Shifting', 'Standard package for office shifting under moving & shifting. Includes trained professionals, standard tools, and service support.', 1182.00, 'INR', 152, NULL, NULL, NULL),
(80, 'Premium Office Shifting', 'Premium package for office shifting under moving & shifting. Includes trained professionals, standard tools, and service support.', 1312.00, 'INR', 185, NULL, NULL, NULL),
(81, 'Basic Furniture Moving', 'Basic package for furniture moving under moving & shifting. Includes trained professionals, standard tools, and service support.', 1048.00, 'INR', 123, NULL, NULL, NULL),
(81, 'Standard Furniture Moving', 'Standard package for furniture moving under moving & shifting. Includes trained professionals, standard tools, and service support.', 1217.00, 'INR', 150, NULL, NULL, NULL),
(81, 'Premium Furniture Moving', 'Premium package for furniture moving under moving & shifting. Includes trained professionals, standard tools, and service support.', 1373.00, 'INR', 190, NULL, NULL, NULL),
(82, 'Basic Vehicle Transport', 'Basic package for vehicle transport under moving & shifting. Includes trained professionals, standard tools, and service support.', 1046.00, 'INR', 123, NULL, NULL, NULL),
(82, 'Standard Vehicle Transport', 'Standard package for vehicle transport under moving & shifting. Includes trained professionals, standard tools, and service support.', 1158.00, 'INR', 153, NULL, NULL, NULL),
(82, 'Premium Vehicle Transport', 'Premium package for vehicle transport under moving & shifting. Includes trained professionals, standard tools, and service support.', 1328.00, 'INR', 184, NULL, NULL, NULL),
(83, 'Basic Yoga', 'Basic package for yoga under fitness & therapy. Includes trained professionals, standard tools, and service support.', 760.00, 'INR', 73, NULL, NULL, NULL),
(83, 'Standard Yoga', 'Standard package for yoga under fitness & therapy. Includes trained professionals, standard tools, and service support.', 910.00, 'INR', 99, NULL, NULL, NULL),
(83, 'Premium Yoga', 'Premium package for yoga under fitness & therapy. Includes trained professionals, standard tools, and service support.', 1028.00, 'INR', 131, NULL, NULL, NULL),
(84, 'Basic Physiotherapy', 'Basic package for physiotherapy under fitness & therapy. Includes trained professionals, standard tools, and service support.', 728.00, 'INR', 65, NULL, NULL, NULL),
(84, 'Standard Physiotherapy', 'Standard package for physiotherapy under fitness & therapy. Includes trained professionals, standard tools, and service support.', 903.00, 'INR', 98, NULL, NULL, NULL),
(84, 'Premium Physiotherapy', 'Premium package for physiotherapy under fitness & therapy. Includes trained professionals, standard tools, and service support.', 1065.00, 'INR', 125, NULL, NULL, NULL),
(85, 'Basic Massage', 'Basic package for massage under fitness & therapy. Includes trained professionals, standard tools, and service support.', 768.00, 'INR', 63, NULL, NULL, NULL),
(85, 'Standard Massage', 'Standard package for massage under fitness & therapy. Includes trained professionals, standard tools, and service support.', 851.00, 'INR', 91, NULL, NULL, NULL),
(85, 'Premium Massage', 'Premium package for massage under fitness & therapy. Includes trained professionals, standard tools, and service support.', 1020.00, 'INR', 132, NULL, NULL, NULL),
(86, 'Basic Posture Correction', 'Basic package for posture correction under fitness & therapy. Includes trained professionals, standard tools, and service support.', 729.00, 'INR', 63, NULL, NULL, NULL),
(86, 'Standard Posture Correction', 'Standard package for posture correction under fitness & therapy. Includes trained professionals, standard tools, and service support.', 859.00, 'INR', 98, NULL, NULL, NULL),
(86, 'Premium Posture Correction', 'Premium package for posture correction under fitness & therapy. Includes trained professionals, standard tools, and service support.', 1046.00, 'INR', 127, NULL, NULL, NULL),
(87, 'Basic Personal Training', 'Basic package for personal training under fitness & therapy. Includes trained professionals, standard tools, and service support.', 763.00, 'INR', 61, NULL, NULL, NULL),
(87, 'Standard Personal Training', 'Standard package for personal training under fitness & therapy. Includes trained professionals, standard tools, and service support.', 862.00, 'INR', 100, NULL, NULL, NULL),
(87, 'Premium Personal Training', 'Premium package for personal training under fitness & therapy. Includes trained professionals, standard tools, and service support.', 1005.00, 'INR', 132, NULL, NULL, NULL),
(88, 'Basic Nutrition', 'Basic package for nutrition under fitness & therapy. Includes trained professionals, standard tools, and service support.', 708.00, 'INR', 69, NULL, NULL, NULL),
(88, 'Standard Nutrition', 'Standard package for nutrition under fitness & therapy. Includes trained professionals, standard tools, and service support.', 882.00, 'INR', 102, NULL, NULL, NULL),
(88, 'Premium Nutrition', 'Premium package for nutrition under fitness & therapy. Includes trained professionals, standard tools, and service support.', 1017.00, 'INR', 134, NULL, NULL, NULL),
(89, 'Basic Meditation', 'Basic package for meditation under fitness & therapy. Includes trained professionals, standard tools, and service support.', 723.00, 'INR', 66, NULL, NULL, NULL),
(89, 'Standard Meditation', 'Standard package for meditation under fitness & therapy. Includes trained professionals, standard tools, and service support.', 893.00, 'INR', 97, NULL, NULL, NULL),
(89, 'Premium Meditation', 'Premium package for meditation under fitness & therapy. Includes trained professionals, standard tools, and service support.', 1006.00, 'INR', 126, NULL, NULL, NULL),
(90, 'Basic Senior Fitness', 'Basic package for senior fitness under fitness & therapy. Includes trained professionals, standard tools, and service support.', 755.00, 'INR', 69, NULL, NULL, NULL),
(90, 'Standard Senior Fitness', 'Standard package for senior fitness under fitness & therapy. Includes trained professionals, standard tools, and service support.', 879.00, 'INR', 90, NULL, NULL, NULL),
(90, 'Premium Senior Fitness', 'Premium package for senior fitness under fitness & therapy. Includes trained professionals, standard tools, and service support.', 999.00, 'INR', 121, NULL, NULL, NULL),
(91, 'Basic Prenatal Care', 'Basic package for prenatal care under fitness & therapy. Includes trained professionals, standard tools, and service support.', 731.00, 'INR', 68, NULL, NULL, NULL),
(91, 'Standard Prenatal Care', 'Standard package for prenatal care under fitness & therapy. Includes trained professionals, standard tools, and service support.', 864.00, 'INR', 98, NULL, NULL, NULL),
(91, 'Premium Prenatal Care', 'Premium package for prenatal care under fitness & therapy. Includes trained professionals, standard tools, and service support.', 1029.00, 'INR', 132, NULL, NULL, NULL),
(92, 'Basic Lawn Mowing', 'Basic package for lawn mowing under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 410.00, 'INR', 69, NULL, NULL, NULL),
(92, 'Standard Lawn Mowing', 'Standard package for lawn mowing under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 615.00, 'INR', 91, NULL, NULL, NULL),
(92, 'Premium Lawn Mowing', 'Premium package for lawn mowing under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 714.00, 'INR', 122, NULL, NULL, NULL),
(93, 'Basic Garden Maintenance', 'Basic package for garden maintenance under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 433.00, 'INR', 64, NULL, NULL, NULL),
(93, 'Standard Garden Maintenance', 'Standard package for garden maintenance under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 562.00, 'INR', 91, NULL, NULL, NULL),
(93, 'Premium Garden Maintenance', 'Premium package for garden maintenance under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 748.00, 'INR', 129, NULL, NULL, NULL),
(94, 'Basic Plant Care', 'Basic package for plant care under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 415.00, 'INR', 63, NULL, NULL, NULL),
(94, 'Standard Plant Care', 'Standard package for plant care under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 572.00, 'INR', 91, NULL, NULL, NULL),
(94, 'Premium Plant Care', 'Premium package for plant care under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 715.00, 'INR', 128, NULL, NULL, NULL),
(95, 'Basic Soil Treatment', 'Basic package for soil treatment under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 449.00, 'INR', 60, NULL, NULL, NULL),
(95, 'Standard Soil Treatment', 'Standard package for soil treatment under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 552.00, 'INR', 90, NULL, NULL, NULL),
(95, 'Premium Soil Treatment', 'Premium package for soil treatment under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 728.00, 'INR', 124, NULL, NULL, NULL),
(96, 'Basic Balcony Gardening', 'Basic package for balcony gardening under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 443.00, 'INR', 73, NULL, NULL, NULL),
(96, 'Standard Balcony Gardening', 'Standard package for balcony gardening under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 598.00, 'INR', 94, NULL, NULL, NULL),
(96, 'Premium Balcony Gardening', 'Premium package for balcony gardening under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 745.00, 'INR', 122, NULL, NULL, NULL),
(97, 'Basic Terrace Gardening', 'Basic package for terrace gardening under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 409.00, 'INR', 61, NULL, NULL, NULL),
(97, 'Standard Terrace Gardening', 'Standard package for terrace gardening under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 612.00, 'INR', 100, NULL, NULL, NULL),
(97, 'Premium Terrace Gardening', 'Premium package for terrace gardening under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 717.00, 'INR', 124, NULL, NULL, NULL),
(98, 'Basic Fence Repair', 'Basic package for fence repair under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 449.00, 'INR', 66, NULL, NULL, NULL),
(98, 'Standard Fence Repair', 'Standard package for fence repair under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 555.00, 'INR', 95, NULL, NULL, NULL),
(98, 'Premium Fence Repair', 'Premium package for fence repair under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 716.00, 'INR', 123, NULL, NULL, NULL),
(99, 'Basic Tree Pruning', 'Basic package for tree pruning under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 462.00, 'INR', 72, NULL, NULL, NULL),
(99, 'Standard Tree Pruning', 'Standard package for tree pruning under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 588.00, 'INR', 99, NULL, NULL, NULL),
(99, 'Premium Tree Pruning', 'Premium package for tree pruning under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 706.00, 'INR', 130, NULL, NULL, NULL),
(100, 'Basic Pest Spray', 'Basic package for pest spray under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 400.00, 'INR', 65, NULL, NULL, NULL),
(100, 'Standard Pest Spray', 'Standard package for pest spray under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 564.00, 'INR', 90, NULL, NULL, NULL),
(100, 'Premium Pest Spray', 'Premium package for pest spray under outdoor & gardening. Includes trained professionals, standard tools, and service support.', 712.00, 'INR', 126, NULL, NULL, NULL),
(106, 'Fruit Facial Glow', 'A refreshing fruit-based facial that brightens and hydrates tired skin.', 799.00, 'INR', 60, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.80, 2140),
(106, 'Hair Spa & Care', 'A deep-conditioning hair spa that repairs damage and restores natural shine.', 899.00, 'INR', 75, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.70, 1560),
(106, 'Full Arms & Legs Waxing', 'Smooth, salon-grade waxing for arms and legs using a gentle wax.', 599.00, 'INR', 45, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.60, 3200),
(106, 'Threading (Eyebrows + Upper Lip)', 'Quick, precise threading for perfectly shaped brows and upper lip.', 149.00, 'INR', 20, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.50, 4100),
(106, 'Manicure & Pedicure', 'A classic mani-pedi that leaves hands and feet soft, neat and polished.', 649.00, 'INR', 60, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.60, 2450),
(106, 'Global Hair Colour', 'Ammonia-friendly global colour application for full, even coverage.', 1299.00, 'INR', 90, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.50, 870),
(107, 'Haircut & Styling', 'A precision haircut and styling from an experienced men''s stylist.', 299.00, 'INR', 30, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop', 4.70, 5200),
(107, 'Beard Shape-up & Trim', 'Sharp beard shaping and trim to keep your look fresh.', 199.00, 'INR', 20, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop', 4.60, 4700),
(107, 'Head & Shoulder Massage', 'A relaxing head and shoulder massage to relieve stress and tension.', 399.00, 'INR', 30, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop', 4.80, 2300),
(107, 'De-Tan Facial for Men', 'A de-tan facial that clears dullness and refreshes sun-exposed skin.', 549.00, 'INR', 45, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop', 4.50, 1340),
(107, 'Beard & Hair Colour', 'Natural-looking colour touch-up for greying hair and beard.', 349.00, 'INR', 30, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop', 4.40, 980),
(108, 'Party Makeup', 'Camera-ready party makeup tailored to your outfit and occasion.', 1499.00, 'INR', 90, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.90, 860),
(108, 'Bridal Makeup (HD)', 'Long-lasting HD bridal makeup with draping and hairstyling included.', 6999.00, 'INR', 150, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.90, 410),
(108, 'Nail Art & Manicure', 'A gel manicure with custom nail art finished by a trained nail artist.', 499.00, 'INR', 40, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.60, 1980),
(108, 'Engagement Makeup', 'Soft-glam engagement makeup designed to photograph beautifully.', 2999.00, 'INR', 100, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.80, 320),
(109, 'Full Home Deep Cleaning', 'A comprehensive deep clean covering every room, kitchen and bathroom.', 3499.00, 'INR', 240, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.80, 6200),
(109, 'Kitchen Deep Cleaning', 'Degreasing and sanitising of chimney, hob, cabinets and countertops.', 899.00, 'INR', 90, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.70, 3100),
(109, 'Bathroom Deep Cleaning', 'Descaling and disinfecting tiles, fittings and fixtures until spotless.', 499.00, 'INR', 60, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.60, 4400),
(109, 'Sofa & Carpet Shampooing', 'A machine shampoo wash to lift dirt and stains from sofas and carpets.', 799.00, 'INR', 75, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.50, 1870),
(109, 'Balcony & Grille Cleaning', 'Scrubbing and de-staining of balcony floors, grilles and railings.', 399.00, 'INR', 40, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.40, 760),
(109, 'Move-in / Move-out Cleaning', 'A thorough top-to-bottom clean to prep a home before or after moving.', 2799.00, 'INR', 180, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.70, 1120),
(110, 'General Pest Control', 'An odourless spray treatment that keeps common household pests away.', 999.00, 'INR', 60, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.60, 2800),
(110, 'Cockroach Control', 'A gel-based treatment that targets cockroaches at the source.', 699.00, 'INR', 45, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.50, 2100),
(110, 'Termite Control', 'An anti-termite treatment with long-lasting protection for wood and walls.', 2499.00, 'INR', 120, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.70, 940),
(110, 'Mosquito Fogging', 'A fogging treatment that clears mosquito breeding spots indoors and out.', 599.00, 'INR', 30, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.40, 1330),
(110, 'Bed Bug Treatment', 'A targeted treatment that eliminates bed bugs from mattresses and furniture.', 1299.00, 'INR', 90, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.50, 640),
(110, 'Rodent Control', 'Safe trapping and sealing to keep rodents out for good.', 899.00, 'INR', 50, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.40, 510),
(111, 'Office Deep Cleaning', 'A full deep clean for workstations, common areas and pantries.', 4999.00, 'INR', 300, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.60, 380),
(111, 'Carpet & Upholstery Cleaning', 'Machine cleaning for office carpets, chairs and fabric partitions.', 1899.00, 'INR', 120, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.50, 210),
(111, 'Sanitization Service', 'Disinfectant fogging across surfaces, desks and high-touch points.', 2499.00, 'INR', 90, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.60, 300),
(112, 'AC General Service', 'A foam-jet cleaning that restores cooling efficiency and airflow.', 549.00, 'INR', 45, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.70, 7100),
(112, 'AC Repair Visit', 'A diagnostic visit to identify and fix cooling or noise issues.', 299.00, 'INR', 30, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.50, 3900),
(112, 'AC Gas Refill', 'A refrigerant top-up for ACs that have lost cooling performance.', 2199.00, 'INR', 90, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.60, 1200),
(112, 'Split AC Installation', 'Professional mounting and installation of a new split AC unit.', 1499.00, 'INR', 120, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.60, 860),
(112, 'Window AC Installation', 'Secure fitting and sealing for a new window AC unit.', 999.00, 'INR', 90, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.50, 540),
(113, 'Refrigerator Repair', 'A diagnostic and repair visit for cooling, noise or leakage issues.', 399.00, 'INR', 45, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.50, 2600),
(113, 'Washing Machine Repair', 'Troubleshooting and repair for drainage, spin or drum issues.', 399.00, 'INR', 45, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.50, 3300),
(113, 'Microwave Repair', 'A repair visit for heating, sparking or control panel problems.', 349.00, 'INR', 30, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.40, 1150),
(113, 'Water Purifier Service', 'A filter check and service to keep your RO purifier running safely.', 449.00, 'INR', 40, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.60, 1980),
(113, 'Chimney Repair & Cleaning', 'Degreasing filters and checking suction for a smoke-free kitchen.', 599.00, 'INR', 50, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.50, 890),
(113, 'Geyser Repair & Service', 'A safety check and repair for heating elements and thermostats.', 449.00, 'INR', 40, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.40, 760),
(114, 'TV Repair', 'A diagnostic visit for display, sound or power issues on any TV.', 449.00, 'INR', 45, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.40, 720),
(114, 'Laptop Repair', 'Hardware and software troubleshooting for slow or malfunctioning laptops.', 599.00, 'INR', 60, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.30, 480),
(114, 'Inverter & Battery Repair', 'Testing and repair to keep your home inverter backup reliable.', 499.00, 'INR', 45, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.40, 390),
(115, 'Switch & Socket Repair', 'Fix or replace faulty switches and sockets safely.', 149.00, 'INR', 20, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.60, 3400),
(115, 'Ceiling Fan Installation', 'Secure mounting and wiring of a new ceiling fan.', 249.00, 'INR', 30, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.60, 2700),
(115, 'House Wiring Inspection', 'A full electrical safety check to catch wiring issues early.', 499.00, 'INR', 60, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.50, 980),
(115, 'MCB & Fuse Repair', 'Diagnosis and repair of tripping MCBs or blown fuses.', 299.00, 'INR', 30, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.50, 1340),
(115, 'Inverter Installation', 'Wiring and setup for a new home inverter and battery backup.', 799.00, 'INR', 75, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.50, 610),
(115, 'CCTV / Video Doorbell Install', 'Mounting and wiring for a smart camera or video doorbell.', 649.00, 'INR', 60, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.60, 540),
(116, 'Tap & Mixer Repair', 'Fix leaking or jammed taps and mixers in the kitchen or bathroom.', 149.00, 'INR', 20, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.60, 3900),
(116, 'Pipe Leakage Repair', 'Locate and seal pipe leaks before they cause water damage.', 349.00, 'INR', 40, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.50, 2200),
(116, 'Toilet & Flush Repair', 'Repair of flush tanks, jets or toilet seat fittings.', 299.00, 'INR', 35, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.50, 1870),
(116, 'Water Tank Cleaning', 'Deep cleaning and disinfection of overhead or underground tanks.', 599.00, 'INR', 60, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.40, 990),
(116, 'Water Heater Installation', 'Safe mounting and plumbing connection for a new geyser.', 549.00, 'INR', 60, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.50, 720),
(116, 'Drainage Cleaning', 'Clearing clogged drains to restore normal water flow.', 449.00, 'INR', 45, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.30, 650),
(117, 'Furniture Assembly', 'Assembly of flat-pack furniture like beds, wardrobes and desks.', 349.00, 'INR', 45, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.60, 1650),
(117, 'Door & Lock Repair', 'Fix sticking doors, loose hinges or faulty locks.', 299.00, 'INR', 30, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.50, 1420),
(117, 'Furniture Repair', 'Repair of wobbly, broken or damaged wooden furniture.', 399.00, 'INR', 40, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.40, 870),
(117, 'Curtain Rod Installation', 'Levelled mounting of curtain rods and brackets on any wall.', 249.00, 'INR', 30, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.50, 610),
(117, 'Wall Shelf Installation', 'Secure fitting of wall-mounted shelves and storage units.', 299.00, 'INR', 35, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.40, 480),
(118, 'Single Room Painting', 'Two coats of premium emulsion for one room''s walls and ceiling.', 3999.00, 'INR', 480, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.60, 610),
(118, 'Full Home Painting', 'A complete interior painting package sized for 2-3 BHK homes.', 24999.00, 'INR', 2400, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.70, 340),
(118, 'Accent Wall Texture Design', 'A textured finish applied to a feature wall for a design accent.', 4999.00, 'INR', 480, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.50, 210),
(118, 'Wood Polish & Varnish', 'Refinishing for doors, furniture and wood trims to restore their shine.', 2499.00, 'INR', 480, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.50, 260),
(118, 'Wall Stencil Art', 'A custom stencil design hand-painted onto a wall of your choice.', 1999.00, 'INR', 300, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.40, 180),
(119, 'Exterior Wall Painting', 'A weatherproof exterior painting package for independent houses.', 18999.00, 'INR', 2040, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.60, 260),
(119, 'Waterproofing Treatment', 'Preventive waterproofing for terraces, walls and bathrooms.', 5999.00, 'INR', 480, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.70, 430),
(119, 'Metal Grill & Gate Painting', 'Anti-rust primer and enamel finish for grilles, gates and railings.', 2999.00, 'INR', 480, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.40, 150);
