-- Insert admin users.

INSERT INTO public.fks_users (external_id, full_name, email, phone1, phone2, password_hash, role, status, created_at, updated_at)
VALUES 
(random_uuid(), 'Folks Admin', 'folks.admin@javalabs.org', '9000000000', NULL, '7c6a180b36896a0a8c02787eeafb0e4c', 'ADMIN', 'ACTIVE', CURRENT_TIMESTAMP, null),
(random_uuid(), 'Node Admin', 'node.admin@javalabs.org', '8000000000', NULL, '6cb75f652a9b52798eb6cf2201057c73', 'ADMIN', 'ACTIVE', CURRENT_TIMESTAMP, null),
(random_uuid(), 'Support Admin', 'support.admin@javalabs.org', '7000000000', NULL, '6cb75f652a9b52798eb6cf2201057c73', 'ADMIN', 'ACTIVE', CURRENT_TIMESTAMP, null);


-- Reference data (Cities where folks is operational) --

--1. Countries

INSERT INTO fks_countries (country_code, country_name, language_code, language, locale_code, currency_code, currency, timezone, created_at, updated_at)
VALUES ('IN', 'India', 'en', 'English', 'en_US', 'INR', 'Indian Rupee', 'Asia/Kolkata', CURRENT_TIMESTAMP, NULL);

-- 2. States

INSERT INTO fks_provinces (country_id, province_name, region, language, created_at, updated_at)
VALUES
    (1, 'Andhra Pradesh',       'SOUTH',     'Telugu',     CURRENT_TIMESTAMP, NULL),
    (1, 'Arunachal Pradesh',    'NORTHEAST', 'English',    CURRENT_TIMESTAMP, NULL),
    (1, 'Assam',                'NORTHEAST', 'Assamese',   CURRENT_TIMESTAMP, NULL),
    (1, 'Bihar',                'EAST',      'Hindi',      CURRENT_TIMESTAMP, NULL),
    (1, 'Chhattisgarh',         'CENTRAL',   'Hindi',      CURRENT_TIMESTAMP, NULL),
    (1, 'Goa',                  'WEST',      'Konkani',    CURRENT_TIMESTAMP, NULL),
    (1, 'Gujarat',              'WEST',      'Gujarati',   CURRENT_TIMESTAMP, NULL),
    (1, 'Haryana',              'NORTH',     'Hindi',      CURRENT_TIMESTAMP, NULL),
    (1, 'Himachal Pradesh',     'NORTH',     'Hindi',      CURRENT_TIMESTAMP, NULL),
    (1, 'Jharkhand',            'EAST',      'Hindi',      CURRENT_TIMESTAMP, NULL),
    (1, 'Karnataka',            'SOUTH',     'Kannada',    CURRENT_TIMESTAMP, NULL),
    (1, 'Kerala',               'SOUTH',     'Malayalam',  CURRENT_TIMESTAMP, NULL),
    (1, 'Madhya Pradesh',       'CENTRAL',   'Hindi',      CURRENT_TIMESTAMP, NULL),
    (1, 'Maharashtra',          'WEST',      'Marathi',    CURRENT_TIMESTAMP, NULL),
    (1, 'Manipur',              'NORTHEAST', 'Meitei',     CURRENT_TIMESTAMP, NULL),
    (1, 'Meghalaya',            'NORTHEAST', 'English',    CURRENT_TIMESTAMP, NULL),
    (1, 'Mizoram',              'NORTHEAST', 'Mizo',       CURRENT_TIMESTAMP, NULL),
    (1, 'Nagaland',             'NORTHEAST', 'English',    CURRENT_TIMESTAMP, NULL),
    (1, 'Odisha',               'EAST',      'Odia',       CURRENT_TIMESTAMP, NULL),
    (1, 'Punjab',               'NORTH',     'Punjabi',    CURRENT_TIMESTAMP, NULL),
    (1, 'Rajasthan',            'NORTH',     'Hindi',      CURRENT_TIMESTAMP, NULL),
    (1, 'Sikkim',               'NORTHEAST', 'English',    CURRENT_TIMESTAMP, NULL),
    (1, 'Tamil Nadu',           'SOUTH',     'Tamil',      CURRENT_TIMESTAMP, NULL),
    (1, 'Telangana',            'SOUTH',     'Telugu',     CURRENT_TIMESTAMP, NULL),
    (1, 'Tripura',              'NORTHEAST', 'Bengali',    CURRENT_TIMESTAMP, NULL),
    (1, 'Uttar Pradesh',        'NORTH',     'Hindi',      CURRENT_TIMESTAMP, NULL),
    (1, 'Uttarakhand',          'NORTH',     'Hindi',      CURRENT_TIMESTAMP, NULL),
    (1, 'West Bengal',          'EAST',      'Bengali',    CURRENT_TIMESTAMP, NULL),

    -- Union Territories
    (1, 'Andaman and Nicobar Islands', 'SOUTH',     'Hindi',      CURRENT_TIMESTAMP, NULL),
    (1, 'Chandigarh',             'NORTH',     'English',    CURRENT_TIMESTAMP, NULL),
    (1, 'Dadra and Nagar Haveli and Daman and Diu', 'WEST',      'Gujarati',   CURRENT_TIMESTAMP, NULL),
    (1, 'Delhi',                  'NORTH',     'Hindi',      CURRENT_TIMESTAMP, NULL),
    (1, 'Jammu and Kashmir',      'NORTH',     'Kashmiri',   CURRENT_TIMESTAMP, NULL),
    (1, 'Ladakh',                 'NORTH',     'English',    CURRENT_TIMESTAMP, NULL),
    (1, 'Lakshadweep',            'SOUTH',     'Malayalam',  CURRENT_TIMESTAMP, NULL),
    (1, 'Puducherry',             'SOUTH',     'Tamil',      CURRENT_TIMESTAMP, NULL);

-- 3. Cities

INSERT INTO fks_cities (province_id, city_name, image_key, status, launched_at, created_at, updated_at)
VALUES
    -- Tier 1 / Major Metros
    (14, 'Mumbai',             NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (32, 'Delhi',              NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (11, 'Bengaluru',          NULL, 'ACTIVE',  NULL, CURRENT_TIMESTAMP, NULL),
    (24, 'Hyderabad',          NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (23, 'Chennai',            NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (28, 'Kolkata',            NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 7, 'Ahmedabad',          NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (14, 'Pune',               NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),

    -- Tier 2 / Major Emerging Cities
    ( 7, 'Surat',              NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 21, 'Jaipur',             NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 26, 'Lucknow',            NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 26, 'Kanpur',             NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 14, 'Nagpur',             NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 13, 'Indore',             NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 14, 'Thane',              NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 13, 'Bhopal',             NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (  1, 'Visakhapatnam',      NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 14, 'Pimpri-Chinchwad',   NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (  4, 'Patna',              NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 26, 'Ghaziabad',          NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 26, 'Agra',               NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (  8, 'Faridabad',          NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 26, 'Varanasi',           NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 33, 'Srinagar',           NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 14, 'Chhatrapati Sambhajinagar', NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 10, 'Dhanbad',            NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 20, 'Amritsar',           NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 14, 'Navi Mumbai',        NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 26, 'Prayagraj',          NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 10, 'Ranchi',             NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 13, 'Jabalpur',           NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 13, 'Gwalior',            NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 23, 'Coimbatore',         NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 21, 'Jodhpur',            NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (  5, 'Raipur',             NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 21, 'Kota',               NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 30, 'Chandigarh',         NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (  3, 'Guwahati',           NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 11, 'Mysuru',             NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (  8, 'Gurugram',           NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 26, 'Noida',              NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 12, 'Kochi',              NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 19, 'Bhubaneswar',        NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (  7, 'Vadodara',           NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 23, 'Madurai',            NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    (  1, 'Vijayawada',         NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 14, 'Nashik',             NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 12, 'Thiruvananthapuram', NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 20, 'Ludhiana',           NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL),
    ( 23, 'Tiruchirappalli',    NULL, 'PLANNED', NULL, CURRENT_TIMESTAMP, NULL);
    

-- 4. Servcing Areas of an Operating City --

INSERT INTO public.fks_neighbourhoods (city_id, locality, pincode, latitude, longitude, is_serviceable, created_at, updated_at)
VALUES
    (3, 'Bengaluru G.P.O.', 560001, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Dr. Ambedkar Veedhi', 560001, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'HighCourt', 560001, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Legislators Home', 560001, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Mahatma Gandhi Road', 560001, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Rajbhavan', 560001, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Vasanthanagar', 560001, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Vidhana Soudha', 560001, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'CMM Court Complex', 560001, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bengaluru Corporation Building', 560002, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bengaluru City', 560002, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Malleswaram', 560003, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Palace Guttahalli', 560003, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Swimming Pool Extn', 560003, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Vyalikaval Extn', 560003, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Basavanagudi', 560004, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Gaviopuram Extension', 560004, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Mavalli', 560004, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Pampamahakavi Road', 560004, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Fraser Town', 560005, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Benson Town', 560006, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'J C Nagar', 560006, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Training Command IAF', 560006, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Agram', 560007, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Air Force Hospital', 560007, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Cambridge Layout', 560008, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'H A L II Stage', 560008, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bengaluru Dist Offices Bldg', 560009, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'K. G. Road', 560009, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Industrial Estate', 560010, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Rajajinagar', 560010, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Rajajinagar IVth Block', 560010, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Jayangar III Block', 560011, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Madhavan Park', 560011, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Science Institute', 560012, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Jalahalli East', 560013, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Jalahalli', 560013, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Jalahalli West', 560015, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Doorvaninagar', 560016, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Krishnarajapuram R S', 560016, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Ramamurthy Nagar', 560016, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'N A L', 560017, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Vimanapura', 560017, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Chamrajpet', 560018, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Goripalya', 560018, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Seshadripuram', 560020, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Gayathrinagar', 560021, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Srirampuram', 560021, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Yeshwanthpur Bazar', 560022, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Yeswanthpura', 560022, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Magadi Road', 560023, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Anandanagar', 560024, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'H A Farm', 560024, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Hebbal Kempapura', 560024, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'CMP Centre And School', 560025, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Museum Road', 560025, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Richmond Town', 560025, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Governmemnt Electric Factory', 560026, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'NAYANDAHALLI', 560026, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Sampangiramnagar', 560027, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Shanthinagar', 560027, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Wilson Garden', 560027, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Dharmaram College', 560029, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Tavarekere', 560029, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Adugodi', 560030, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'P and T Colony Kavalbyrasandra', 560032, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'R T Nagar', 560032, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Maruthi Sevanagar', 560033, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Koramangala I Block', 560034, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Koramangala', 560034, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'St. Johns Medical College', 560034, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Carmelram', 560035, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Devasandra', 560036, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Krishnarajapuram', 560036, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Doddanekkundi', 560037, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kundalahalli', 560037, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Marathahalli Colony', 560037, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Rameshnagar', 560037, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Indiranagar', 560038, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Chandra Lay Out', 560040, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Vijayanagar East', 560040, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Vijayanagar', 560040, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Jayanagar East', 560041, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Jayanagar', 560041, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Tilaknagar', 560041, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Sivan Chetty Gardens', 560042, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Banaswadi', 560043, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Jalavayuvihar', 560043, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kalyananagar', 560043, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Arabic College', 560045, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Austin Town', 560047, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Viveknagar', 560047, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Hoodi', 560048, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Mahadevapura', 560048, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bhattarahalli', 560049, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bidrahalli', 560049, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Ashoknagar', 560050, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Banashankari', 560050, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Dasarahalli(Srinagar)', 560050, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'State Bank Of Mysuru Colony', 560050, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'H K P Road', 560051, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Chickpet', 560053, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Mathikere', 560054, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Msrit', 560054, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Sri Chowdeshwari', 560054, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Malleswaram West', 560055, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bengaluru vishwavidyalaya', 560056, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Mallathahalli', 560056, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Peenya Dasarahalli', 560057, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Laggere', 560058, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Peenya I Stage', 560058, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Peenya Small Industries', 560058, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Rv Niketan', 560059, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Chudenapura', 560060, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kengeri', 560060, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Chikkalasandra', 560061, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Subramanyapura', 560061, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Doddakallasandra', 560062, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Konanakunte', 560062, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'A F Station Yelahanka', 560063, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'BSF Campus Yelahanka', 560063, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Attur', 560064, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Jakkur', 560064, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Rajanakunte', 560064, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Singanayakanahalli', 560064, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Yelahanka', 560064, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Yelahanka Satellite Town', 560064, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'G K V K', 560065, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'E P I P', 560066, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Whitefield', 560066, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kadugodi', 560067, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bommanahalli', 560068, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'KUDLU', 560068, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Madivala', 560068, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Singasandra', 560068, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'B Sk II Stage', 560070, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Padmanabhnagar', 560070, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Thyagarajnagar', 560070, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Domlur', 560071, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Nagarbhavi', 560072, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Nagarbhavi II Stage', 560072, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'BAGALGUNTE', 560073, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Chikkabidarkal', 560073, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Nagasandra', 560073, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Nelakadiranahalli', 560073, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kumbalagodu', 560074, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kumbalgodu Gollahalli', 560074, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Ramohalli', 560074, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Jeevanbhimanagar', 560075, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'New Thippasandra', 560075, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bannerghatta Road', 560076, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'JP Nagar VIII phase', 560076, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Mico Layout', 560076, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Mount St Joseph', 560076, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Doddagubbi', 560077, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Dr. Shivarama Karanth Nagar', 560077, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kannur', 560077, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kothanur', 560077, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'J P Nagar', 560078, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'JP Nagar III Phase', 560078, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Yelachenahalli', 560078, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Basaveshwaranagar', 560079, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kamakshipalya', 560079, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'K H B Colony', 560079, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Sadashivanagar', 560080, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Chandapura', 560081, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Thataguni', 560082, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Udaypura', 560082, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bannerghatta', 560083, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Gottigere', 560083, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kalkere', 560083, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Ragihalli', 560083, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Sakalavara', 560083, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Lingarajapuram', 560084, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'St. Thomas Town', 560084, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Banashankari III Stage', 560085, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Girinagar', 560085, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kathriguppe', 560085, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Mahalakshmipuram Layout', 560086, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'West of Chord Road II stage', 560086, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Gunjur', 560087, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Panathur', 560087, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Vartur', 560087, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Hessarghatta', 560088, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Byatha', 560089, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Hessarghatta Lake', 560089, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kakolu', 560089, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Shivakote', 560089, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Chikkabanavara', 560090, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Silvepura', 560090, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bapagrama', 560091, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Herohalli', 560091, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Sir M.VISVESVARAYA NAGARA', 560091, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Viswaneedam', 560091, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Amruthahalli', 560092, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Byatarayanapura', 560092, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kodigehalli', 560092, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Sahakaranagar', 560092, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'C V Raman Nagar', 560093, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'ISRO Anthariksha Bhavan', 560094, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'R M V Extension II Stage', 560094, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Koramangala VI Bk', 560095, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Nandinilayout', 560096, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Vidyaranyapura', 560097, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Channasandra', 560098, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Pattanagere', 560098, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Rajarajeshwarinagar', 560098, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bommasandra Industrial Estate', 560099, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Huskur', 560099, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Electronics City', 560100, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'HSR Layout', 560102, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bellandur', 560103, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Hampinagar', 560104, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Haragadde', 560105, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Hennagara', 560105, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Hulimangala', 560105, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Jigani', 560105, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kallubalu', 560105, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Achitnagar', 560107, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Anjanapura', 560108, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Thalaghattapura', 560109, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Ullalu Upanagar', 560110, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kumaraswamy Layout', 560111, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kodigehalli', 560112, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Horamavu', 560113, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Begur', 560114, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kannamangala', 560115, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bolare', 560116, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kaggalipura', 560116, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Somanhalli', 560116, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Taralu', 560116, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Thattekuppe', 560116, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Singanayakanahalli', 560119, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Kempegowda International Airport', 560300, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Anekal', 562106, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bestamaranahalli', 562106, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Byagadadenahalli', 562106, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Guddanahalli', 562106, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Indalawadi', 562106, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Samandur', 562106, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Sidihoskote', 562106, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Thammanayakanahalli', 562106, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Vanakanahalli', 562106, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Attibele', 562107, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Bidaraguppe', 562107, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Mayasandra', 562107, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Neralur', 562107, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Yadavanahalli', 562107, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Cholanayakanahally', 562120, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL),
    (3, 'Dommasandra', 562125, NULL, NULL, 1, CURRENT_TIMESTAMP, NULL);

