-- Insert admin users.

INSERT INTO public.fks_users (external_id, full_name, email, phone1, phone2, password_hash, role, status, created_at, updated_at)
VALUES 
(RANDOM_UUID(), 'Folks Admin', 'folks.admin@javalabs.org', '9000000000', NULL, '7c6a180b36896a0a8c02787eeafb0e4c', 'ADMIN', 'ACTIVE', current_timestamp, null),
(RANDOM_UUID(), 'Node Admin', 'node.admin@javalabs.org', '8000000000', NULL, '6cb75f652a9b52798eb6cf2201057c73', 'ADMIN', 'ACTIVE', current_timestamp, null),
(RANDOM_UUID(), 'Support Admin', 'support.admin@javalabs.org', '7000000000', NULL, '6cb75f652a9b52798eb6cf2201057c73', 'ADMIN', 'ACTIVE', current_timestamp, null);


-- Generated from categories-data.js
-- Category and subcategory IDs are generated by PostgreSQL identity columns.
-- BEGIN/COMMIT keeps the three dependent inserts atomic.
BEGIN;

-- 1. Top-level categories
INSERT INTO fks_categories (name, parent_id, icon, tag_line, image) VALUES
    ('Salon & Makeup', NULL, 'scissors', 'Professional grooming and beauty services at home.', 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop'),
    ('Cleaning & Pest Control', NULL, 'broom', 'Deep cleaning and pest treatments that actually last.', 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop'),
    ('Appliance Repair', NULL, 'wrench', 'Fast, reliable repairs for the appliances you rely on daily.', 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop'),
    ('Electrician, Plumbing & Carpentry', NULL, 'bolt', 'Trusted hands for wiring, leaks and everyday fixes.', 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop'),
    ('Painting & Décor', NULL, 'paint-roller', 'Fresh coats and finishing touches, handled end to end.', 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop');

-- 2. Subcategories
INSERT INTO fks_categories (name, parent_id, icon, tag_line, image)
SELECT v.name, p.category_id, NULL, NULL, v.image
FROM (VALUES
    ('Salon & Makeup', 'Women''s Salon', 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop'),
    ('Salon & Makeup', 'Men''s Salon', 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop'),
    ('Salon & Makeup', 'Bridal & Party Makeup', 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop'),
    ('Cleaning & Pest Control', 'Home Cleaning', 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop'),
    ('Cleaning & Pest Control', 'Pest Control', 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop'),
    ('Cleaning & Pest Control', 'Office Cleaning', 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop'),
    ('Appliance Repair', 'AC Service & Repair', 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop'),
    ('Appliance Repair', 'Kitchen & Home Appliances', 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop'),
    ('Appliance Repair', 'Electronics Repair', 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop'),
    ('Electrician, Plumbing & Carpentry', 'Electrician', 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop'),
    ('Electrician, Plumbing & Carpentry', 'Plumbing', 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop'),
    ('Electrician, Plumbing & Carpentry', 'Carpentry', 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop'),
    ('Painting & Décor', 'Interior Painting', 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop'),
    ('Painting & Décor', 'Exterior Painting', 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop')) AS v(parent_name, name, image)
JOIN fks_categories p ON p.parent_id IS NULL AND p.name = v.parent_name;

-- 3. Services
INSERT INTO fks_services (category_id, name, description, base_price, duration_minutes, image, rating_avg, reviews)
SELECT sc.category_id, v.name, v.description, v.base_price, v.duration_minutes, v.image, v.rating_avg, v.reviews
FROM (VALUES
    ('Salon & Makeup', 'Women''s Salon', 'Fruit Facial Glow', 'A refreshing fruit-based facial that brightens and hydrates tired skin.', 799, 60, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.8, 2140),
    ('Salon & Makeup', 'Women''s Salon', 'Hair Spa & Care', 'A deep-conditioning hair spa that repairs damage and restores natural shine.', 899, 75, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.7, 1560),
    ('Salon & Makeup', 'Women''s Salon', 'Full Arms & Legs Waxing', 'Smooth, salon-grade waxing for arms and legs using a gentle wax.', 599, 45, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.6, 3200),
    ('Salon & Makeup', 'Women''s Salon', 'Threading (Eyebrows + Upper Lip)', 'Quick, precise threading for perfectly shaped brows and upper lip.', 149, 20, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.5, 4100),
    ('Salon & Makeup', 'Women''s Salon', 'Manicure & Pedicure', 'A classic mani-pedi that leaves hands and feet soft, neat and polished.', 649, 60, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.6, 2450),
    ('Salon & Makeup', 'Women''s Salon', 'Global Hair Colour', 'Ammonia-friendly global colour application for full, even coverage.', 1299, 90, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.5, 870),
    ('Salon & Makeup', 'Men''s Salon', 'Haircut & Styling', 'A precision haircut and styling from an experienced men''s stylist.', 299, 30, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop', 4.7, 5200),
    ('Salon & Makeup', 'Men''s Salon', 'Beard Shape-up & Trim', 'Sharp beard shaping and trim to keep your look fresh.', 199, 20, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop', 4.6, 4700),
    ('Salon & Makeup', 'Men''s Salon', 'Head & Shoulder Massage', 'A relaxing head and shoulder massage to relieve stress and tension.', 399, 30, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop', 4.8, 2300),
    ('Salon & Makeup', 'Men''s Salon', 'De-Tan Facial for Men', 'A de-tan facial that clears dullness and refreshes sun-exposed skin.', 549, 45, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop', 4.5, 1340),
    ('Salon & Makeup', 'Men''s Salon', 'Beard & Hair Colour', 'Natural-looking colour touch-up for greying hair and beard.', 349, 30, 'https://images.unsplash.com/photo-1647140655214-e4a2d914971f?w=800&q=80&auto=format&fit=crop', 4.4, 980),
    ('Salon & Makeup', 'Bridal & Party Makeup', 'Party Makeup', 'Camera-ready party makeup tailored to your outfit and occasion.', 1499, 90, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.9, 860),
    ('Salon & Makeup', 'Bridal & Party Makeup', 'Bridal Makeup (HD)', 'Long-lasting HD bridal makeup with draping and hairstyling included.', 6999, 150, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.9, 410),
    ('Salon & Makeup', 'Bridal & Party Makeup', 'Nail Art & Manicure', 'A gel manicure with custom nail art finished by a trained nail artist.', 499, 40, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.6, 1980),
    ('Salon & Makeup', 'Bridal & Party Makeup', 'Engagement Makeup', 'Soft-glam engagement makeup designed to photograph beautifully.', 2999, 100, 'https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&q=80&auto=format&fit=crop', 4.8, 320),
    ('Cleaning & Pest Control', 'Home Cleaning', 'Full Home Deep Cleaning', 'A comprehensive deep clean covering every room, kitchen and bathroom.', 3499, 240, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.8, 6200),
    ('Cleaning & Pest Control', 'Home Cleaning', 'Kitchen Deep Cleaning', 'Degreasing and sanitising of chimney, hob, cabinets and countertops.', 899, 90, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.7, 3100),
    ('Cleaning & Pest Control', 'Home Cleaning', 'Bathroom Deep Cleaning', 'Descaling and disinfecting tiles, fittings and fixtures until spotless.', 499, 60, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.6, 4400),
    ('Cleaning & Pest Control', 'Home Cleaning', 'Sofa & Carpet Shampooing', 'A machine shampoo wash to lift dirt and stains from sofas and carpets.', 799, 75, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.5, 1870),
    ('Cleaning & Pest Control', 'Home Cleaning', 'Balcony & Grille Cleaning', 'Scrubbing and de-staining of balcony floors, grilles and railings.', 399, 40, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.4, 760),
    ('Cleaning & Pest Control', 'Home Cleaning', 'Move-in / Move-out Cleaning', 'A thorough top-to-bottom clean to prep a home before or after moving.', 2799, 180, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.7, 1120),
    ('Cleaning & Pest Control', 'Pest Control', 'General Pest Control', 'An odourless spray treatment that keeps common household pests away.', 999, 60, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.6, 2800),
    ('Cleaning & Pest Control', 'Pest Control', 'Cockroach Control', 'A gel-based treatment that targets cockroaches at the source.', 699, 45, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.5, 2100),
    ('Cleaning & Pest Control', 'Pest Control', 'Termite Control', 'An anti-termite treatment with long-lasting protection for wood and walls.', 2499, 120, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.7, 940),
    ('Cleaning & Pest Control', 'Pest Control', 'Mosquito Fogging', 'A fogging treatment that clears mosquito breeding spots indoors and out.', 599, 30, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.4, 1330),
    ('Cleaning & Pest Control', 'Pest Control', 'Bed Bug Treatment', 'A targeted treatment that eliminates bed bugs from mattresses and furniture.', 1299, 90, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.5, 640),
    ('Cleaning & Pest Control', 'Pest Control', 'Rodent Control', 'Safe trapping and sealing to keep rodents out for good.', 899, 50, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.4, 510),
    ('Cleaning & Pest Control', 'Office Cleaning', 'Office Deep Cleaning', 'A full deep clean for workstations, common areas and pantries.', 4999, 300, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.6, 380),
    ('Cleaning & Pest Control', 'Office Cleaning', 'Carpet & Upholstery Cleaning', 'Machine cleaning for office carpets, chairs and fabric partitions.', 1899, 120, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.5, 210),
    ('Cleaning & Pest Control', 'Office Cleaning', 'Sanitization Service', 'Disinfectant fogging across surfaces, desks and high-touch points.', 2499, 90, 'https://images.unsplash.com/photo-1647381518264-97ff1835026f?w=800&q=80&auto=format&fit=crop', 4.6, 300),
    ('Appliance Repair', 'AC Service & Repair', 'AC General Service', 'A foam-jet cleaning that restores cooling efficiency and airflow.', 549, 45, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.7, 7100),
    ('Appliance Repair', 'AC Service & Repair', 'AC Repair Visit', 'A diagnostic visit to identify and fix cooling or noise issues.', 299, 30, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.5, 3900),
    ('Appliance Repair', 'AC Service & Repair', 'AC Gas Refill', 'A refrigerant top-up for ACs that have lost cooling performance.', 2199, 90, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.6, 1200),
    ('Appliance Repair', 'AC Service & Repair', 'Split AC Installation', 'Professional mounting and installation of a new split AC unit.', 1499, 120, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.6, 860),
    ('Appliance Repair', 'AC Service & Repair', 'Window AC Installation', 'Secure fitting and sealing for a new window AC unit.', 999, 90, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.5, 540),
    ('Appliance Repair', 'Kitchen & Home Appliances', 'Refrigerator Repair', 'A diagnostic and repair visit for cooling, noise or leakage issues.', 399, 45, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.5, 2600),
    ('Appliance Repair', 'Kitchen & Home Appliances', 'Washing Machine Repair', 'Troubleshooting and repair for drainage, spin or drum issues.', 399, 45, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.5, 3300),
    ('Appliance Repair', 'Kitchen & Home Appliances', 'Microwave Repair', 'A repair visit for heating, sparking or control panel problems.', 349, 30, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.4, 1150),
    ('Appliance Repair', 'Kitchen & Home Appliances', 'Water Purifier Service', 'A filter check and service to keep your RO purifier running safely.', 449, 40, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.6, 1980),
    ('Appliance Repair', 'Kitchen & Home Appliances', 'Chimney Repair & Cleaning', 'Degreasing filters and checking suction for a smoke-free kitchen.', 599, 50, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.5, 890),
    ('Appliance Repair', 'Kitchen & Home Appliances', 'Geyser Repair & Service', 'A safety check and repair for heating elements and thermostats.', 449, 40, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.4, 760),
    ('Appliance Repair', 'Electronics Repair', 'TV Repair', 'A diagnostic visit for display, sound or power issues on any TV.', 449, 45, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.4, 720),
    ('Appliance Repair', 'Electronics Repair', 'Laptop Repair', 'Hardware and software troubleshooting for slow or malfunctioning laptops.', 599, 60, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.3, 480),
    ('Appliance Repair', 'Electronics Repair', 'Inverter & Battery Repair', 'Testing and repair to keep your home inverter backup reliable.', 499, 45, 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=800&q=80&auto=format&fit=crop', 4.4, 390),
    ('Electrician, Plumbing & Carpentry', 'Electrician', 'Switch & Socket Repair', 'Fix or replace faulty switches and sockets safely.', 149, 20, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.6, 3400),
    ('Electrician, Plumbing & Carpentry', 'Electrician', 'Ceiling Fan Installation', 'Secure mounting and wiring of a new ceiling fan.', 249, 30, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.6, 2700),
    ('Electrician, Plumbing & Carpentry', 'Electrician', 'House Wiring Inspection', 'A full electrical safety check to catch wiring issues early.', 499, 60, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.5, 980),
    ('Electrician, Plumbing & Carpentry', 'Electrician', 'MCB & Fuse Repair', 'Diagnosis and repair of tripping MCBs or blown fuses.', 299, 30, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.5, 1340),
    ('Electrician, Plumbing & Carpentry', 'Electrician', 'Inverter Installation', 'Wiring and setup for a new home inverter and battery backup.', 799, 75, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.5, 610),
    ('Electrician, Plumbing & Carpentry', 'Electrician', 'CCTV / Video Doorbell Install', 'Mounting and wiring for a smart camera or video doorbell.', 649, 60, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.6, 540),
    ('Electrician, Plumbing & Carpentry', 'Plumbing', 'Tap & Mixer Repair', 'Fix leaking or jammed taps and mixers in the kitchen or bathroom.', 149, 20, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.6, 3900),
    ('Electrician, Plumbing & Carpentry', 'Plumbing', 'Pipe Leakage Repair', 'Locate and seal pipe leaks before they cause water damage.', 349, 40, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.5, 2200),
    ('Electrician, Plumbing & Carpentry', 'Plumbing', 'Toilet & Flush Repair', 'Repair of flush tanks, jets or toilet seat fittings.', 299, 35, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.5, 1870),
    ('Electrician, Plumbing & Carpentry', 'Plumbing', 'Water Tank Cleaning', 'Deep cleaning and disinfection of overhead or underground tanks.', 599, 60, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.4, 990),
    ('Electrician, Plumbing & Carpentry', 'Plumbing', 'Water Heater Installation', 'Safe mounting and plumbing connection for a new geyser.', 549, 60, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.5, 720),
    ('Electrician, Plumbing & Carpentry', 'Plumbing', 'Drainage Cleaning', 'Clearing clogged drains to restore normal water flow.', 449, 45, 'https://images.unsplash.com/photo-1676210134190-3f2c0d5cf58d?w=800&q=80&auto=format&fit=crop', 4.3, 650),
    ('Electrician, Plumbing & Carpentry', 'Carpentry', 'Furniture Assembly', 'Assembly of flat-pack furniture like beds, wardrobes and desks.', 349, 45, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.6, 1650),
    ('Electrician, Plumbing & Carpentry', 'Carpentry', 'Door & Lock Repair', 'Fix sticking doors, loose hinges or faulty locks.', 299, 30, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.5, 1420),
    ('Electrician, Plumbing & Carpentry', 'Carpentry', 'Furniture Repair', 'Repair of wobbly, broken or damaged wooden furniture.', 399, 40, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.4, 870),
    ('Electrician, Plumbing & Carpentry', 'Carpentry', 'Curtain Rod Installation', 'Levelled mounting of curtain rods and brackets on any wall.', 249, 30, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.5, 610),
    ('Electrician, Plumbing & Carpentry', 'Carpentry', 'Wall Shelf Installation', 'Secure fitting of wall-mounted shelves and storage units.', 299, 35, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80&auto=format&fit=crop', 4.4, 480),
    ('Painting & Décor', 'Interior Painting', 'Single Room Painting', 'Two coats of premium emulsion for one room''s walls and ceiling.', 3999, 480, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.6, 610),
    ('Painting & Décor', 'Interior Painting', 'Full Home Painting', 'A complete interior painting package sized for 2-3 BHK homes.', 24999, 2400, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.7, 340),
    ('Painting & Décor', 'Interior Painting', 'Accent Wall Texture Design', 'A textured finish applied to a feature wall for a design accent.', 4999, 480, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.5, 210),
    ('Painting & Décor', 'Interior Painting', 'Wood Polish & Varnish', 'Refinishing for doors, furniture and wood trims to restore their shine.', 2499, 480, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.5, 260),
    ('Painting & Décor', 'Interior Painting', 'Wall Stencil Art', 'A custom stencil design hand-painted onto a wall of your choice.', 1999, 300, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.4, 180),
    ('Painting & Décor', 'Exterior Painting', 'Exterior Wall Painting', 'A weatherproof exterior painting package for independent houses.', 18999, 2040, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.6, 260),
    ('Painting & Décor', 'Exterior Painting', 'Waterproofing Treatment', 'Preventive waterproofing for terraces, walls and bathrooms.', 5999, 480, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.7, 430),
    ('Painting & Décor', 'Exterior Painting', 'Metal Grill & Gate Painting', 'Anti-rust primer and enamel finish for grilles, gates and railings.', 2999, 480, 'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?w=800&q=80&auto=format&fit=crop', 4.4, 150)) AS v(parent_name, subcategory_name, name, description, base_price, duration_minutes, image, rating_avg, reviews)
JOIN fks_categories p ON p.parent_id IS NULL AND p.name = v.parent_name
JOIN fks_categories sc ON sc.parent_id = p.category_id AND sc.name = v.subcategory_name;
